# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: date-setter-app
#   namespace: flux-system
# spec:
#   interval: 24h
#   ref:
#     branch: main
#   url: https://github.com/nikimanoledaki/date-setter-app
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: ./date-setter-app
#   namespace: default
# spec:
#   dependsOn:
#   - name: kube-prometheus-stack
#   - name: kepler
#   interval: 24h
#   path: ./date-setter-app
#   prune: true
#   wait: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system