---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kepler
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  url: https://github.com/sustainable-computing-io/kepler
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kepler
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus-setup
  interval: 5m
  path: ./kepler
  prune: true
  wait: true
