---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kepler
  namespace: flux-system
spec:
  dependsOn:
  - name: kube-prometheus
  interval: 5m
  path: ./clusters/kepler
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system