---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 30m0s
  ref:
    branch: main
  url: https://github.com/prometheus-operator/kube-prometheus
  ignore: |
    alertmanager-main
    alertmanager-alertmanager.yaml
    alertmanager-networkPolicy.yaml
    alertmanager-podDisruptionBudget.yaml
    alertmanager-prometheusRule.yaml
    alertmanager-secret.yaml
    alertmanager-service.yaml
    alertmanager-serviceAccount.yaml
    alertmanager-serviceMonitor.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus-setup
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifests/setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 5m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifests
  dependsOn:
  - name: kube-prometheus-setup
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  timeout: 5m0s
  wait: true
