# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: GitRepository
# metadata:
#   name: flux-monitoring
#   namespace: flux-system
# spec:
#   interval: 30m0s
#   ref:
#     branch: main
#   url: https://github.com/fluxcd/flux2
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
# kind: Kustomization
# metadata:
#   name: kube-prometheus-stack
#   namespace: flux-system
# spec:
#   interval: 1h0m0s
#   path: ./manifests/monitoring/kube-prometheus-stack
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-monitoring
#   timeout: 5m0s
#   wait: true