apiVersion: v1
kind: Namespace
metadata:
  name: kepler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kepler-clusterrole
  namespace: kepler
rules:
- apiGroups: [""]
  resources:
  - nodes/metrics # access /metrics/resource
  - nodes/proxy # access /pods
  - nodes/stats # access /pods
  verbs:
  - 'get'
  - 'watch'
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kepler-clusterrole-binding
  namespace: kepler
roleRef:
  kind: ClusterRole
  name: kepler-clusterrole
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: ServiceAccount
  name: kepler-sa
  namespace: kepler
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kepler-sa
  namespace: kepler
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler-exporter
  namespace: kepler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: kepler-exporter
    spec:
      hostNetwork: true
      serviceAccountName: kepler-sa
      containers:
      - name: kepler-exporter
        image: quay.io/sustainable_computing_io/kepler:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        command:
        - /usr/bin/kepler
        - -address
        - 0.0.0.0:9102
        - -enable-gpu=true
        - -enable-cgroup-id=true
        ports:
        - containerPort: 9102
          hostPort: 9102
          name: http
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /sys
          name: tracing
        - mountPath: /proc
          name: proc
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: tracing
        hostPath:
          path: /sys
          type: Directory
      - name: proc
        hostPath:
          path: /proc
          type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: kepler-exporter
  namespace: kepler
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
  ports:
  - name: http
    port: 9102
    targetPort: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kepler-exporter
  name: kepler-exporter
  namespace: kepler
spec:
  endpoints:
  - interval: 3s
    port: http
    relabelings:
    - action: replace
      regex: (.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: instance
    scheme: http
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: kepler-exporter
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes/metrics
  - verbs:
      - get
    nonResourceURLs:
      - /metrics
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  namespace: kepler
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - services
      - endpoints
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
    resources:
      - ingresses
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  namespace: kepler
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/instance: k8s
    app.kubernetes.io/name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s